### ISSUE TITLE
Reference Styles for LaTeX

### ISSUE THREAD

**Issue by HughP** [dcmi/dcpapers-templates#2]
@nishad I am using the LaTeX template for DC2022. I am wondering how to implement the references correctly. If I use `apalike` with bibtex but that style does not include the full first name as the style guide requires. 

I thought about using natbib as both bibtex and natbib are supported per the style guide, but the line in the preamble which is supposed to be uncommented make the file have a numbered reference system which also is not according the to the style guide.

```
%     \PassOptionsToPackage{numbers, compress}{natbib}
```

Can you point me to the correct style to include? I'm using overleaf.

**Comment by nishad** [comment]
@HughP the [original template](https://github.com/dcmi/dcpapers-templates/blob/main/templates/conferences/DC-2022/Microsoft-Word/DC-2022_template_v1.3.dot) for DCPapaers was based on APA-6 and recommended to clearly spell out the full first name in the references. 

**You can safely ignore this style recommendation** on references if you plan to use `natbib` or `biblatex` and continue with **Last name, First initial(s).** by following APA-7. Please make sure that consistency is maintained for the whole paper.

Also, as the reference section of the sample latex template recommends, please use [`biblatex`](https://ctan.org/pkg/biblatex). `biblatex` has [better APA support](https://ctan.org/pkg/biblatex-apa).
