### ISSUE TITLE
URLs and DOI in LaTeX bibliography stylesheet

### ISSUE THREAD

**Issue by HughP** [dcmi/dcpapers-templates#3]
Greetings @nishad 

One more thing about the LaTeX bibliography stylesheet. When using bibtex and apalike style, no DOIs or URLs appear. So in bibliographic style for DC Conference papers, adding DOIs and URLs seems fairly important. This is only my second paper using LaTeX and we didn't use bibtex on my previous paper... So I'm afraid I'm not too much help at this point in time on evolving the template.

**Comment by nishad** [comment]
As mentioned in https://github.com/dcmi/dcpapers-templates/issues/2#issuecomment-1120786632, please use [`biblatex`](https://ctan.org/pkg/biblatex). `biblatex` has [better APA support](https://ctan.org/pkg/biblatex-apa). `applike` may not be supporting DOI and links properly.
